[package]
name = "packet-sniffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.8.0"
colored = "2.0"
ndarray = "0.15"
ndarray-stats = "0.4"
chrono = "0.4"